name: Build and Push donkey 3.1 Docker image 

on:
  push:
    branches: 
      - main
      - dev
    paths:
      - 'donkey31/Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tag
        id: determine-tag
        run: echo "::set-output name=tag::$(if [ $GITHUB_REF == 'refs/heads/main' ]; then echo 'latest'; else echo 'dev'; fi)"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/donkey31:${{ steps.determine-tag.outputs.tag }}
          # tags: ${{ secrets.DOCKERHUB_USERNAME }}/donkey31:latest
          file: donkey31/Dockerfile
